// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByZKZDUcaKh-E1EB8txrHwaijO2rnoWiU',
    appId: '1:944006642493:web:a374f550d374501b146354',
    messagingSenderId: '944006642493',
    projectId: 'neto-66101',
    authDomain: 'neto-66101.firebaseapp.com',
    storageBucket: 'neto-66101.firebasestorage.app',
    measurementId: 'G-63S0XPKEYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCejqFuXOmam5KyyfpM_EvT5msHSSPIwo',
    appId: '1:944006642493:android:82ff0dd1e1edbbc1146354',
    messagingSenderId: '944006642493',
    projectId: 'neto-66101',
    storageBucket: 'neto-66101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQPTKDcey2aIcW92MjLSNHf4jqACUeDrA',
    appId: '1:944006642493:ios:02c5e32a75ceb759146354',
    messagingSenderId: '944006642493',
    projectId: 'neto-66101',
    storageBucket: 'neto-66101.firebasestorage.app',
    iosBundleId: 'com.example.netoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQPTKDcey2aIcW92MjLSNHf4jqACUeDrA',
    appId: '1:944006642493:ios:02c5e32a75ceb759146354',
    messagingSenderId: '944006642493',
    projectId: 'neto-66101',
    storageBucket: 'neto-66101.firebasestorage.app',
    iosBundleId: 'com.example.netoApp',
  );
}
